#!/usr/bin/env ruby

require 'sparql/client'
require 'pp'

q4 = <<-EOS
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT ?org ?team ?conference ?label ?color1 ?color2 ?capacity ?firstseason ?headcoach ?stadium ?stadiumlabel ?hclabel
WHERE {
  ?org skos:broader <http://dbpedia.org/resource/Category:NCAA_Division_I_FBS_football_teams> .
  ?team dcterms:subject ?org .
  ?team rdfs:label ?label .
  ?team dbpedia2:conferencedisplay ?conference .
  ?team dbpedia2:color1hex ?color1 .
  ?team dbpedia2:color2hex ?color2 .
  ?team dbpedia2:stadcapacity ?capacity .
  ?team dbpedia2:headcoachdisplay ?headcoach .
  ?team dbpedia2:stadium ?stadium .
  ?team dbpedia2:firstyear ?firstseason .
  OPTIONAL { ?headcoach rdfs:label ?hclabel }
  OPTIONAL { ?stadium foaf:name ?stadiumlabel }
  FILTER(LANG(?label) = 'en' and regex(str(?team), "[_football]$") and xsd:integer(?capacity) > 0)
}
EOS

require 'sparql/client'
client = SPARQL::Client.new('http://dbpedia.org/sparql')
results = client.query(q4)

results.each_solution do |sol|
  out = {}
  sol.each_binding do |key, val|
    next if [:org, :team].include?(key)
    out[key] = val.to_s
  end
  puts out
end
